[package]
name = "zk"
version = "0.1.0"
edition = "2021"

[dependencies]
zk-methods = { path = "methods" }

risc0-zkvm = { version = "0.20" }
serde = "1.0"

serde_json = "1.0"
serde_derive = "1.0"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
metal = ["risc0-zkvm/metal"]
